# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'airship-adapter-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for airship-adapter-sample
  pod 'GimbalAirshipAdapter', :path => "../GimbalAirshipAdapter.podspec"

end
